version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: badol
      POSTGRES_PASSWORD: Badol2465
      POSTGRES_DB: crud_database
  app:
    image: my-node-app
    ports:
      - 13000:3000